In [22]:
# univariate lstm example
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from array import array
import csv

In [23]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
    X, y =[],[]
    for i in range(len(timeseries_data)):
        # find the end of this pattern
        end_ix = i + n_features
        # check if we are beyond the sequence
        if end_ix > len(timeseries_data)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [24]:
# define input sequence
timeseries_data = [43000,
43700,
44400,
45100,
45800,
46500,
47200,
47900,
48600,
49300,
50000,
50700,
51400,
52100,
52800,
53500,
54200,
54900,
55600,
56300,
57100,
57900,
58700,
59500,
60300,
61100,
61900,
62700,
63500,
64300,
65100,
65900,
66700,
67500,
68300,
69100,
69900,
71000,
72100,
73200,
74300,
75400,
76500,
77600,
78700,
79800,
80900,
82000,
83100,
84200,
85300,
86400,
87500,
88600,
89700,
90800,
91900,
93000,
94100,
95200,
96300,
97400,
98500,
99600,
100700,
101800,
102900,
103200,
103500,
103800,
104100,
104400,
104700,
105000,
105800,
106600,
107400,
108200,
109000,
109800,
110600,
111400,
112200,
113000,
113800,
114600,
115400,
116200,
117000,
118000,
119000,
120000,
121000,
122000,
123000,
124000,
125000,
126000,
127300,
128600,
129900,
131200,
132500,
133800,
135100,
136400,
137700,
139000,
140300,
141600,
142900,
144200,
145500,
146800,
148100,
150200,
152300,
154400,
156500,
158600,
160700,
162800,
164900,
167000,
169100,
171200,
173300,
175400,
177500,
179600,
182100,
184600,
187100,
189600,
192100,
195600,
199100,
202600,
206100,
209600,
213100,
216600,
220100,
223600,
227100,
230600,
234100,
237600,
241100,
244600,
248100,
251600,
255100,
258600,
262100
]


# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [25]:
print(X),print(y)

[[ 43000  43700  44400]
 [ 43700  44400  45100]
 [ 44400  45100  45800]
 [ 45100  45800  46500]
 [ 45800  46500  47200]
 [ 46500  47200  47900]
 [ 47200  47900  48600]
 [ 47900  48600  49300]
 [ 48600  49300  50000]
 [ 49300  50000  50700]
 [ 50000  50700  51400]
 [ 50700  51400  52100]
 [ 51400  52100  52800]
 [ 52100  52800  53500]
 [ 52800  53500  54200]
 [ 53500  54200  54900]
 [ 54200  54900  55600]
 [ 54900  55600  56300]
 [ 55600  56300  57100]
 [ 56300  57100  57900]
 [ 57100  57900  58700]
 [ 57900  58700  59500]
 [ 58700  59500  60300]
 [ 59500  60300  61100]
 [ 60300  61100  61900]
 [ 61100  61900  62700]
 [ 61900  62700  63500]
 [ 62700  63500  64300]
 [ 63500  64300  65100]
 [ 64300  65100  65900]
 [ 65100  65900  66700]
 [ 65900  66700  67500]
 [ 66700  67500  68300]
 [ 67500  68300  69100]
 [ 68300  69100  69900]
 [ 69100  69900  71000]
 [ 69900  71000  72100]
 [ 71000  72100  73200]
 [ 72100  73200  74300]
 [ 73200  74300  75400]
 [ 74300  75400  76500]
 [ 75400  76500 

(None, None)

In [26]:
X.shape

(152, 3)

In [27]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [28]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300
5/5 [==============================] - 6s 11ms/step - loss: 16767579136.0000
Epoch 2/300
5/5 [==============================] - 0s 12ms/step - loss: 15873792000.0000
Epoch 3/300
5/5 [==============================] - 0s 14ms/step - loss: 15137895424.0000
Epoch 4/300
5/5 [==============================] - 0s 13ms/step - loss: 14607134720.0000
Epoch 5/300
5/5 [==============================] - 0s 11ms/step - loss: 14075575296.0000
Epoch 6/300
5/5 [==============================] - 0s 14ms/step - loss: 13503876096.0000
Epoch 7/300
5/5 [==============================] - 0s 14ms/step - loss: 13440971776.0000
Epoch 8/300
5/5 [==============================] - 0s 14ms/step - loss: 13626858496.0000
Epoch 9/300
5/5 [==============================] - 0s 12ms/step - loss: 12919299072.0000
Epoch 10/300
5/5 [==============================] - 0s 13ms/step - loss: 12197534720.0000
Epoch 11/300
5/5 [==============================] - 0s 12ms/step - loss: 11332760576.0000
Epoch 12/300
5/5 [=

5/5 [==============================] - 0s 10ms/step - loss: 1053576.3750
Epoch 96/300
5/5 [==============================] - 0s 11ms/step - loss: 1053381.6250
Epoch 97/300
5/5 [==============================] - 0s 11ms/step - loss: 1054793.1250
Epoch 98/300
5/5 [==============================] - 0s 10ms/step - loss: 1053776.0000
Epoch 99/300
5/5 [==============================] - 0s 9ms/step - loss: 1053937.0000
Epoch 100/300
5/5 [==============================] - 0s 10ms/step - loss: 1053967.7500
Epoch 101/300
5/5 [==============================] - 0s 10ms/step - loss: 1053753.1250
Epoch 102/300
5/5 [==============================] - 0s 10ms/step - loss: 1053266.7500
Epoch 103/300
5/5 [==============================] - 0s 10ms/step - loss: 1053896.0000
Epoch 104/300
5/5 [==============================] - 0s 10ms/step - loss: 1054007.5000
Epoch 105/300
5/5 [==============================] - 0s 10ms/step - loss: 1053002.5000
Epoch 106/300
5/5 [==============================] - 0s 10ms/s

5/5 [==============================] - 0s 17ms/step - loss: 1055904.0000
Epoch 190/300
5/5 [==============================] - 0s 13ms/step - loss: 1052432.5000
Epoch 191/300
5/5 [==============================] - 0s 11ms/step - loss: 1054831.6250
Epoch 192/300
5/5 [==============================] - 0s 11ms/step - loss: 1056550.5000
Epoch 193/300
5/5 [==============================] - 0s 11ms/step - loss: 1053091.5000
Epoch 194/300
5/5 [==============================] - 0s 12ms/step - loss: 1053546.1250
Epoch 195/300
5/5 [==============================] - 0s 11ms/step - loss: 1053802.0000
Epoch 196/300
5/5 [==============================] - 0s 12ms/step - loss: 1053765.1250
Epoch 197/300
5/5 [==============================] - 0s 12ms/step - loss: 1056304.6250
Epoch 198/300
5/5 [==============================] - 0s 12ms/step - loss: 1052898.5000
Epoch 199/300
5/5 [==============================] - 0s 11ms/step - loss: 1054452.3750
Epoch 200/300
5/5 [==============================] - 0s 1

5/5 [==============================] - 0s 10ms/step - loss: 1055570.1250
Epoch 284/300
5/5 [==============================] - 0s 11ms/step - loss: 1052610.5000
Epoch 285/300
5/5 [==============================] - 0s 12ms/step - loss: 1056634.0000
Epoch 286/300
5/5 [==============================] - 0s 11ms/step - loss: 1052823.5000
Epoch 287/300
5/5 [==============================] - 0s 11ms/step - loss: 1053663.0000
Epoch 288/300
5/5 [==============================] - 0s 12ms/step - loss: 1055124.1250
Epoch 289/300
5/5 [==============================] - 0s 11ms/step - loss: 1057553.8750
Epoch 290/300
5/5 [==============================] - 0s 11ms/step - loss: 1053236.2500
Epoch 291/300
5/5 [==============================] - 0s 11ms/step - loss: 1055490.0000
Epoch 292/300
5/5 [==============================] - 0s 11ms/step - loss: 1056875.7500
Epoch 293/300
5/5 [==============================] - 0s 12ms/step - loss: 1057523.6250
Epoch 294/300
5/5 [==============================] - 0s 1

In [29]:
# demonstrate prediction for next 36 months
x_input = np.array([255100,
258600,
262100])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<36):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} month input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} month output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[264941.44]
1 month input [258600.     262100.     264941.4375]
1 month output [[268437.47]]
2 month input [262100.      264941.4375  268437.46875]
2 month output [[271839.03]]
3 month input [264941.44 268437.47 271839.03]
3 month output [[275058.53]]
4 month input [268437.47 271839.03 275058.53]
4 month output [[278584.34]]
5 month input [271839.03 275058.53 278584.34]
5 month output [[282051.94]]
6 month input [275058.53 278584.34 282051.94]
6 month output [[285502.5]]
7 month input [278584.34 282051.94 285502.5 ]
7 month output [[289103.25]]
8 month input [282051.94 285502.5  289103.25]
8 month output [[292691.03]]
9 month input [285502.5  289103.25 292691.03]
9 month output [[296313.28]]
10 month input [289103.25 292691.03 296313.28]
10 month output [[300021.03]]
11 month input [292691.03 296313.28 300021.03]
11 month output [[303746.25]]
12 month input [296313.28 300021.03 303746.25]
12 month output [[307519.8]]
13 month input [300021.03 303746.25 307519.8 ]
13 month output [[3113

In [30]:
timeseries_data

[43000,
 43700,
 44400,
 45100,
 45800,
 46500,
 47200,
 47900,
 48600,
 49300,
 50000,
 50700,
 51400,
 52100,
 52800,
 53500,
 54200,
 54900,
 55600,
 56300,
 57100,
 57900,
 58700,
 59500,
 60300,
 61100,
 61900,
 62700,
 63500,
 64300,
 65100,
 65900,
 66700,
 67500,
 68300,
 69100,
 69900,
 71000,
 72100,
 73200,
 74300,
 75400,
 76500,
 77600,
 78700,
 79800,
 80900,
 82000,
 83100,
 84200,
 85300,
 86400,
 87500,
 88600,
 89700,
 90800,
 91900,
 93000,
 94100,
 95200,
 96300,
 97400,
 98500,
 99600,
 100700,
 101800,
 102900,
 103200,
 103500,
 103800,
 104100,
 104400,
 104700,
 105000,
 105800,
 106600,
 107400,
 108200,
 109000,
 109800,
 110600,
 111400,
 112200,
 113000,
 113800,
 114600,
 115400,
 116200,
 117000,
 118000,
 119000,
 120000,
 121000,
 122000,
 123000,
 124000,
 125000,
 126000,
 127300,
 128600,
 129900,
 131200,
 132500,
 133800,
 135100,
 136400,
 137700,
 139000,
 140300,
 141600,
 142900,
 144200,
 145500,
 146800,
 148100,
 150200,
 152300,
 154400,
 1

In [31]:
len(timeseries_data)

155

In [32]:
lst_output

[264941.44,
 268437.47,
 271839.03,
 275058.53,
 278584.34,
 282051.94,
 285502.5,
 289103.25,
 292691.03,
 296313.28,
 300021.03,
 303746.25,
 307519.8,
 311354.4,
 315223.7,
 319144.34,
 323118.22,
 327135.97,
 331206.0,
 335327.78,
 339498.6,
 343722.6,
 347999.28,
 352328.34,
 356711.88,
 361149.88,
 365642.8,
 370191.88,
 374797.5,
 379460.34,
 384181.22,
 388960.88,
 393799.9,
 398699.22,
 403659.44,
 408681.4]

In [33]:
with open('reber60gradecsv.csv', 'w') as f:
    writer = csv.writer(f, lineterminator = '\n')
    
    for val in lst_output:
        writer.writerow([val])


In [34]:
temp_input

[393799.9, 398699.22, 403659.44, 408681.4]

In [35]:
import matplotlib.pyplot as plt

In [36]:
day_new=np.arange(1,155)
day_pred=np.arange(155,165)

In [ ]:
plt.plot(day_new,timeseries_data)
plt.plot(day_pred,lst_output)